
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-autoscale
  template:
    metadata:
      labels:
        app: go-autoscale
    spec:
      containers:
      - name: go-autoscale
        image: alifsn/go-autoscale:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
